//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrassDuckFF.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class League
    {
        public int leagueID { get; set; }
        public string leaguename { get; set; }
        public Nullable<int> commissID { get; set; }
        public Nullable<double> passyrdsval { get; set; }
        public Nullable<double> passtdsval { get; set; }
        public Nullable<double> passintsval { get; set; }
        public Nullable<double> rushyrdsval { get; set; }
        public Nullable<double> rushtdsval { get; set; }
        public Nullable<double> recrecval { get; set; }
        public Nullable<double> recyrdsval { get; set; }
        public Nullable<double> rectdsval { get; set; }
        public Nullable<double> defsackval { get; set; }
        public Nullable<double> defintsval { get; set; }
        public Nullable<double> deftds { get; set; }
        public Nullable<double> deffumrecval { get; set; }
        public Nullable<double> kfgmadeval { get; set; }
        public Nullable<double> kfgattemptval { get; set; }
        public Nullable<double> kexpmadeval { get; set; }
        public Nullable<double> kexpattemptval { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Team Team { get; set; }
    }
}
