//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrassDuckFF.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.Teams = new HashSet<Team>();
        }
    
        public int playerID { get; set; }
        public string playername { get; set; }
        public string team { get; set; }
        public string position { get; set; }
        public Nullable<double> weeknum { get; set; }
        public string opponent { get; set; }
        public Nullable<double> passyrds { get; set; }
        public Nullable<double> passtds { get; set; }
        public Nullable<double> passints { get; set; }
        public Nullable<double> rushyrds { get; set; }
        public Nullable<double> rushtds { get; set; }
        public Nullable<double> recrec { get; set; }
        public Nullable<double> recyrds { get; set; }
        public Nullable<double> rectds { get; set; }
        public Nullable<double> defsack { get; set; }
        public Nullable<double> defints { get; set; }
        public Nullable<double> deftds { get; set; }
        public Nullable<double> deffumrec { get; set; }
        public Nullable<double> kfgmade { get; set; }
        public Nullable<double> kfgattempt { get; set; }
        public Nullable<double> kexpmade { get; set; }
        public Nullable<double> kexpattempt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team> Teams { get; set; }
    }
}
